export const FIELD_LABELS: Record<string, string> = {
  programming: 'プログラミング',
  math:        '数学',
  english:     '英語',
  art:         'アート',
  music:       '音楽',
  science:     '科学',
  physics:     '物理',
  chemistry:   '化学',
  biology:     '生物',
  history:     '歴史',
  geography:   '地理',
  japanese:    '国語',
  ethics:      '倫理・哲学',
  economics:   '経済',
};
