name: "ci"
# description: "testing, linting ,compling..."

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: bun i
      - name: Run build
        run: bun build
      - name: Run tests
        run: bun test
      # - name: Run lint
      #   run: bun lint
